-- MySQL Script generated by MySQL Workbench
-- Fri Apr  1 20:24:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`workers' union`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`workers' union` (
  `name` INT NOT NULL,
  `foundation date` DATETIME NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`airport` (
  `uniqe code` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `national code` INT NOT NULL,
  `workers' union_name` INT NOT NULL,
  `airportcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`uniqe code`, `workers' union_name`),
  INDEX `fk_airport_workers' union1_idx` (`workers' union_name` ASC) VISIBLE,
  CONSTRAINT `fk_airport_workers' union1`
    FOREIGN KEY (`workers' union_name`)
    REFERENCES `mydb`.`workers' union` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`technician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`technician` (
  `id number` INT NOT NULL,
  `first name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone number` INT NOT NULL,
  `salary` INT NOT NULL,
  `airport_uniqe code` INT NOT NULL,
  `workers' union_name` INT NOT NULL,
  PRIMARY KEY (`id number`, `airport_uniqe code`, `workers' union_name`),
  INDEX `fk_technician_workers' union1_idx` (`workers' union_name` ASC) VISIBLE,
  CONSTRAINT `fk_technician_workers' union1`
    FOREIGN KEY (`workers' union_name`)
    REFERENCES `mydb`.`workers' union` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`model` (
  `constractor name` VARCHAR(45) NOT NULL,
  `number of seats` INT NOT NULL,
  `wheight` INT NOT NULL,
  `model name` VARCHAR(45) NOT NULL,
  `technician_id number` INT NOT NULL,
  `technician_airport_uniqe code` INT NOT NULL,
  PRIMARY KEY (`model name`, `technician_id number`, `technician_airport_uniqe code`),
  INDEX `fk_model_technician1_idx` (`technician_id number` ASC, `technician_airport_uniqe code` ASC) VISIBLE,
  CONSTRAINT `fk_model_technician1`
    FOREIGN KEY (`technician_id number` , `technician_airport_uniqe code`)
    REFERENCES `mydb`.`technician` (`id number` , `airport_uniqe code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`airplane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`airplane` (
  `code` INT NOT NULL,
  `airport_uniqe code` INT NOT NULL,
  `model_model name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`code`, `airport_uniqe code`, `model_model name`),
  INDEX `fk_airplane_airport_idx` (`airport_uniqe code` ASC) VISIBLE,
  INDEX `fk_airplane_model1_idx` (`model_model name` ASC) VISIBLE,
  CONSTRAINT `fk_airplane_airport`
    FOREIGN KEY (`airport_uniqe code`)
    REFERENCES `mydb`.`airport` (`uniqe code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_airplane_model1`
    FOREIGN KEY (`model_model name`)
    REFERENCES `mydb`.`model` (`model name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`airline companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`airline companies` (
  `name` VARCHAR(45) NOT NULL,
  `country of origin` VARCHAR(45) NOT NULL,
  `national code` INT NOT NULL,
  `active` TINYINT NULL,
  PRIMARY KEY (`national code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manifest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manifest` (
  `flight id` INT NOT NULL,
  PRIMARY KEY (`flight id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`flight` (
  `airport of origin` VARCHAR(45) NOT NULL,
  `destination airport` VARCHAR(45) NOT NULL,
  `departure` DATETIME NOT NULL,
  `arrival` DATETIME NOT NULL,
  `flight id` INT NOT NULL,
  `airline companies_national code` INT NOT NULL,
  `airport_uniqe code` INT NOT NULL,
  `manifest_flight id` INT NOT NULL,
  PRIMARY KEY (`flight id`, `airline companies_national code`, `airport_uniqe code`, `manifest_flight id`),
  INDEX `fk_flights_airline companies1_idx` (`airline companies_national code` ASC) VISIBLE,
  INDEX `fk_flights_airport1_idx` (`airport_uniqe code` ASC) VISIBLE,
  INDEX `fk_flights_manifest1_idx` (`manifest_flight id` ASC) VISIBLE,
  CONSTRAINT `fk_flights_airline companies1`
    FOREIGN KEY (`airline companies_national code`)
    REFERENCES `mydb`.`airline companies` (`national code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flights_airport1`
    FOREIGN KEY (`airport_uniqe code`)
    REFERENCES `mydb`.`airport` (`uniqe code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flights_manifest1`
    FOREIGN KEY (`manifest_flight id`)
    REFERENCES `mydb`.`manifest` (`flight id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`menu` (
  `seat type` VARCHAR(45) NOT NULL,
  `seat number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`seat type`, `seat number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reshearch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reshearch` (
  `title` VARCHAR(45) NOT NULL,
  `flight type` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `human_email` VARCHAR(45) NOT NULL,
  `websites` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`title`, `flight type`, `date`, `human_email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`human`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`human` (
  `first name` VARCHAR(45) NOT NULL,
  `last name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone number` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `reshearch_title` VARCHAR(45) NOT NULL,
  `reshearch_flight type` VARCHAR(45) NOT NULL,
  `reshearch_date` DATETIME NOT NULL,
  `reshearch_human_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`, `reshearch_title`, `reshearch_flight type`, `reshearch_date`, `reshearch_human_email`),
  INDEX `fk_human_reshearch1_idx` (`reshearch_title` ASC, `reshearch_flight type` ASC, `reshearch_date` ASC, `reshearch_human_email` ASC) VISIBLE,
  CONSTRAINT `fk_human_reshearch1`
    FOREIGN KEY (`reshearch_title` , `reshearch_flight type` , `reshearch_date` , `reshearch_human_email`)
    REFERENCES `mydb`.`reshearch` (`title` , `flight type` , `date` , `human_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ticket` (
  `QR-code` BLOB NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`QR-code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservation` (
  `booking code` VARCHAR(45) NOT NULL,
  `seat type` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `comments` VARCHAR(45) NOT NULL,
  `reshearch_title` VARCHAR(45) NOT NULL,
  `reshearch_flight type` VARCHAR(45) NOT NULL,
  `reshearch_date` DATETIME NOT NULL,
  `reshearch_human_email` VARCHAR(45) NOT NULL,
  `ticket_QR-code` BLOB NOT NULL,
  `menu_seat type` VARCHAR(45) NOT NULL,
  `menu_seat number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`reshearch_title`, `reshearch_flight type`, `reshearch_date`, `reshearch_human_email`, `booking code`, `ticket_QR-code`),
  INDEX `fk_reservation_ticket1_idx` (`ticket_QR-code` ASC) VISIBLE,
  INDEX `fk_reservation_menu1_idx` (`menu_seat type` ASC, `menu_seat number` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_reshearch1`
    FOREIGN KEY (`reshearch_title` , `reshearch_flight type` , `reshearch_date` , `reshearch_human_email`)
    REFERENCES `mydb`.`reshearch` (`title` , `flight type` , `date` , `human_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_ticket1`
    FOREIGN KEY (`ticket_QR-code`)
    REFERENCES `mydb`.`ticket` (`QR-code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_menu1`
    FOREIGN KEY (`menu_seat type` , `menu_seat number`)
    REFERENCES `mydb`.`menu` (`seat type` , `seat number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`passenger` (
  `first name` VARCHAR(45) NOT NULL,
  `last name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `passport code` INT NOT NULL,
  `telephone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `ticket_QR-code` BLOB NOT NULL,
  `manifest_flight id` INT NOT NULL,
  PRIMARY KEY (`passport code`, `ticket_QR-code`, `manifest_flight id`),
  INDEX `fk_passenger_ticket1_idx` (`ticket_QR-code` ASC) VISIBLE,
  INDEX `fk_passenger_manifest1_idx` (`manifest_flight id` ASC) VISIBLE,
  CONSTRAINT `fk_passenger_ticket1`
    FOREIGN KEY (`ticket_QR-code`)
    REFERENCES `mydb`.`ticket` (`QR-code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_passenger_manifest1`
    FOREIGN KEY (`manifest_flight id`)
    REFERENCES `mydb`.`manifest` (`flight id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vaccine certificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vaccine certificate` (
  `dose number` INT NOT NULL,
  `date of last dose` DATETIME NOT NULL,
  `vaccine QR-code` BLOB NOT NULL,
  `human_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`vaccine QR-code`, `human_email`),
  INDEX `fk_vaccine certificate_human1_idx` (`human_email` ASC) VISIBLE,
  CONSTRAINT `fk_vaccine certificate_human1`
    FOREIGN KEY (`human_email`)
    REFERENCES `mydb`.`human` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`auditors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auditors` (
  `name` VARCHAR(45) NOT NULL,
  `id number` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `date of medical check up` DATETIME NOT NULL,
  `workers' union_name` INT NOT NULL,
  PRIMARY KEY (`name`, `workers' union_name`),
  INDEX `fk_auditors_workers' union1_idx` (`workers' union_name` ASC) VISIBLE,
  CONSTRAINT `fk_auditors_workers' union1`
    FOREIGN KEY (`workers' union_name`)
    REFERENCES `mydb`.`workers' union` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`checking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`checking` (
  `YPA code` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `maximum grade` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `hours` INT NOT NULL,
  `grade` INT NOT NULL,
  `technician_id number` INT NOT NULL,
  `technician_airport_uniqe code` INT NOT NULL,
  `technician_workers' union_name` INT NOT NULL,
  PRIMARY KEY (`YPA code`, `technician_id number`, `technician_airport_uniqe code`, `technician_workers' union_name`),
  INDEX `fk_checking_technician1_idx` (`technician_id number` ASC, `technician_airport_uniqe code` ASC, `technician_workers' union_name` ASC) VISIBLE,
  CONSTRAINT `fk_checking_technician1`
    FOREIGN KEY (`technician_id number` , `technician_airport_uniqe code` , `technician_workers' union_name`)
    REFERENCES `mydb`.`technician` (`id number` , `airport_uniqe code` , `workers' union_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
